spring:
  jpa:
    hibernate:
      database-platform: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: update
      show_sql: true
    open-in-view: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 15MB
      max-request-size: 15MB
  config:
    additional-location: classpath:application-secret.yml

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    org.springframework.web: DEBUG
    org.springframework.web.filter: DEBUG
    org.springframework.boot.context.config: DEBUG

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
